# Generated by Django 6.0.1 on 2026-01-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Publicación de Texto'), ('IMAGEN', 'Foto/Imagen'), ('VIDEO', 'Video'), ('LINK', 'Enlace (Instagram/Facebook/X)')], default='TEXTO', max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('contenido_texto', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mural/fotos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='mural/videos/')),
                ('url_externa', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_origen', models.CharField(help_text='Ciudad/País desde donde se publica', max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
